// <auto-generated />
using System;
using MemeFolderN.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MemeFolderN.Data.Migrations
{
    [DbContext(typeof(MemeFolderNDbContext))]
    partial class MemeFolderNDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("MemeFolderN.Core.Models.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("MemeFolderN.Core.Models.Meme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiniImagePath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Memes");
                });

            modelBuilder.Entity("MemeFolderN.Core.Models.MemeTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MemeTags");
                });

            modelBuilder.Entity("MemeFolderN.Core.Models.MemeTagNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemeTagId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemeId");

                    b.HasIndex("MemeTagId");

                    b.ToTable("MemeTagNodes");
                });

            modelBuilder.Entity("MemeFolderN.Core.Models.Folder", b =>
                {
                    b.HasOne("MemeFolderN.Core.Models.Folder", "ParentFolder")
                        .WithMany("Folders")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("MemeFolderN.Core.Models.Meme", b =>
                {
                    b.HasOne("MemeFolderN.Core.Models.Folder", "ParentFolder")
                        .WithMany("Memes")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("MemeFolderN.Core.Models.MemeTagNode", b =>
                {
                    b.HasOne("MemeFolderN.Core.Models.Meme", "Meme")
                        .WithMany("TagNodes")
                        .HasForeignKey("MemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemeFolderN.Core.Models.MemeTag", "MemeTag")
                        .WithMany()
                        .HasForeignKey("MemeTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meme");

                    b.Navigation("MemeTag");
                });

            modelBuilder.Entity("MemeFolderN.Core.Models.Folder", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("Memes");
                });

            modelBuilder.Entity("MemeFolderN.Core.Models.Meme", b =>
                {
                    b.Navigation("TagNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
